version: '3'
services:

  poll :
    builds : ./poll
    links :
    - redis
    restar : always
    environment :
    - REDIS_HOSTNAME=redis
    ports : 
    - 5000:80
    networks :
    - poll-tier

  redis :
    image : "redis:alpine"
    restart : always
    expose :
    - "6379"
    environment :
    - POLL_HOSTNAME=poll
    - WORKER_HOSTNAME=worker
    networks :
    - poll-tier
    - back-tier

  worker :
    builds : ./worker
    links :
    - redis
    - db
    restart : always
    environment :
    - DB_HOSTNAME=db
    - REDIS_HOSTNAME=redis
    networks :
    - back-tier
    ports :
    - 5002:80

  db :
    image : postgres:latest
    restar : always
    ports :
    - "5433:5432"

  result :
    builds : ./result
    links :
    - db
    restart : always
    environment :
    - DB_HOSTNAME=db
    networks :
    - result-tier
    ports :
    - 5001:80

  networks :
  - result-tier
  - back-tier

  volumes :
  - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  - db-data:/usr/share/db

  environment :
  - WORKER_HOSTNAME=worker
  - RESULT_HOSTNAME=result
  - POSTGRES_PASSWORD=password
  - POSTGRES_USER=postgres

volumes :
  db-data :
    driver : local

networks:
  poll-tier :
    driver : bridge
  
  result-tier :
    driver : bridge
  
  back-tier :
    driver : bridge
